# Generated by Django 4.2.dev20221028064633 on 2023-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_prescription_status_alter_atm_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
